# Generated by Django 4.0.2 on 2022-02-26 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='view',
            old_name='loaction',
            new_name='location',
        ),
    ]
