# Generated by Django 4.0.2 on 2022-02-27 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rename_loaction_view_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('event', models.CharField(choices=[('I', 'Indoor'), ('O', 'Outdoor'), ('R', 'Remote')], default='I', max_length=1)),
                ('view', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.view')),
            ],
        ),
    ]
