# Generated by Django 4.0.2 on 2022-02-28 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_star_alter_event_options_alter_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='view',
            name='stars',
            field=models.ManyToManyField(to='main_app.Star'),
        ),
    ]
